server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keys/keystore.p12
    key-store-password: Latinica.1
    key-store-type: PKCS12
    key-alias: tomcat
    trust-store: classpath:keys/cacerts
    trust-store-password: testtest
  certificate:
    serial: 1009697567, 81076418332334433471467571647819559628, 96259972520886039836715359477840487195, 132145755450301565074331139870923558714, 93791718698785438451096221151509119784

mail:
  username: activation@secinto.com
  password: S2S.secinto.18.AT
  imap:
    host: imap.ionos.de
    auth: true
    socketFactory:
      port: 993
      class: javax.net.ssl.SSLSocketFactory
  smtp:
    auth: true
    host: smtp.ionos.de
    port: 587
    
spring:
  profiles:
    active: prod,default
  main:
    banner-mode: "off"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: s2s
      
license:
  filepath: temp/license/
  privateKey: keys/private.key
  publicKey: keys/public.key
---
spring:
  profiles: test
  data:
    mongodb:
      database: s2s_test
