baseProtocol: https
baseHost:  localhost
basePort: 51001/s2s
basePortWeb: 51003
usersAPI: /api/users
loginAPI: /api/login
reportsAPI: /api/reports
queryAPI: /api/config/query
deviceAPI: /api/device
packetAPI: /api/packet
stepAPI: /api/steps
processorAPI: /api/processors
licenseAPI: /api/license
serviceAPI: /api/service
groupAPI: /api/group
