baseProtocol: https
#baseHost:  simple2secure.info
#basePort: 51001/s2s
#basePortWeb: 51003
baseHost: localhost
basePort: 8443
basePortWeb: 9000
usersAPI: /api/users
loginAPI: /api/login
reportsAPI: /api/reports
queryAPI: /api/query
deviceAPI: /api/device
packetAPI: /api/packet
stepAPI: /api/steps
processorAPI: /api/processors
licenseAPI: /api/license
serviceAPI: /api/service
groupAPI: /api/group
trustedCertificates: ['1009697567', '93791718698785438451096221151509119784','132145755450301565074331139870923558714','288059177155078140545935159080460680977916', '13298795840390663119752826058995181320', '91299735575339953335919266965803778155']
